### PR TITLE
Fix list item icon position

### PR DESCRIPTION
**Pull request by benedikt-richter**
### Summary of changes

The position of icon indicating whether a list item is added manually is fixed for empty list items. Further, the list item is extracted into a separate component.

### Context and reason for change

Fix: #1374

### How can the changes be tested

Before:
Screenshot 2023-02-03 at 12 07 11

After:
Screenshot 2023-02-03 at 11 47 03

### CODE REVIEW

**Review by lennartclaas — APPROVED** [review]
Looks good. Just two minor suggestions: 
1. We could prevent adding a new list item if only unsuitable characters are given, e.g., whitespace and dashes.
2. We could rename the new `ListWithAttributesListItem` component to `ListWithAttributesItem`. Having 'list' in the name twice sounds a bit redundant to me.

**Review by vasily-pozdnyakov — CHANGES_REQUESTED** [review]
Items with the same name allow multiple choice, it is intended behaviour?
image

**Comment by benedikt-richter** [comment]
> Looks good. Just two minor suggestions:
> 
>     1. We could prevent adding a new list item if only unsuitable characters are given, e.g., whitespace and dashes.
> 
>     2. We could rename the new `ListWithAttributesListItem` component to `ListWithAttributesItem`. Having 'list' in the name twice sounds a bit redundant to me.

Regarding the first one, I've implemented it for white spaces. Would not do for "-". We would have to provide an exact requirement for package names instead. E.g. what about "?" or "r-t"?
Regarding the second one, this would clash with the respective type

**Comment by benedikt-richter** [comment]
@vasily-pozdnyakov created #1385

**Review by vasily-pozdnyakov — APPROVED** [review]
lgtm

**Comment by lennartclaas** [comment]
👍

**Pull request merged**
