### PR TITLE
fix(bug)-added two sets of icons for dark and light mode

### LINKED ISSUE #1684: Menu bar icons are not visible in light mode
## Context
In #1674 top bar menu icons were introduced.

## Issue
The icons look fine on MacOs, however they are not visible in light mode on Windows:
image

## Ideas
This can be fixed by:
* Find icons with a good color which will work fine on different systems and in dark/light mode
* OR add dark icons to use in light mode and write a logic to decide which icons set to use.

### PR DESCRIPTION
**Pull request by tarunsamanta2k20**
Context
In https://github.com/opossum-tool/OpossumUI/pull/1674 top bar menu icons were introduced.

closes #1684 

Issue
The icons look fine on MacOs, however they are not visible in light mode on Windows:
image

Ideas
This can be fixed by:

Find icons with a good color which will work fine on different systems and in dark/light mode
OR add dark icons to use in light mode and write a logic to decide which icons set to use.

### CODE REVIEW

**Comment by tarunsamanta2k20** [comment]
@vasily-pozdnyakov @benedikt-richter check and let me know if it works.

**Review by benedikt-richter — APPROVED** [review]
Works and looks great!
Thanks for that new feature.

**Review by vasily-pozdnyakov — APPROVED** [review]
nice, thx!

**Comment by tarunsamanta2k20** [comment]
@benedikt-richter please add me as a member of your organization. I want to contribute more in the future.

**Pull request merged**
